# Site settings
title: "Ellaina's Site"
description: "Computer Engineering Student @ The University of British Columbia"
url:  "https://ellayx.github.io" # Actual base url of the website
baseurl: ""                    # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Ellaina Ding"
  email: "ellaina.yxding@gmail.com"
  url: ""
permalink: pretty
permalink: /:title
keywords: [podcast, jekyll]
lang: en

#Plugins
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap, jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 5
  title: ':title - page :num'
  permalink: '/page:num/'
  sort_field: 'date'
  sort_reverse: true
  collection: 'posts'  # optional, defaults to _posts

#Pagination
#paginate: 5
#paginate_path: "/page-:num/"

#Sass
sass:
  style: compressed
  sourcemap: never

#SEO

social:
  name: Ellaina


