analytics-id: 
#Pages
pages:
  - {name: 'Experience', link: '/experience/'}
  - {name: 'Projects', link: '/projects/'}
  - {name: 'Hobbies', link: '/hobbies/'}
  - {name: 'GitHub', link: 'https://github.com/ellayx'}


social:
  - {icon: 'youtube', link: '#'}  
  - {icon: 'envelope', link: 'mailto:ellaina.yxding@gmail.com'}
  - {icon: 'linkedin', link: "#"}



translate-date: false 
shownotes: true
